name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test  # Собираем без запуска тестов

      - name: Start SUT application
        run: |
          java -jar ./artifacts/app-order.jar &
          echo $! > app.pid
          sleep 10 # Даем время приложению запуститься
          # Проверяем что приложение запустилось
          curl -f http://localhost:9999 || exit 1

      - name: Run tests
        run: ./gradlew test  # Теперь запускаем тесты отдельно

      - name: Stop SUT application
        run: |
          if [ -f app.pid ]; then
            kill $(cat app.pid) || true
            rm app.pid
          fi